name: Trigger GitLab Pipeline

on:
  push:
    branches:
      - main

jobs:
  trigger-gitlab-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitLab Pipeline
        env:
          GITLAB_TOKEN: 'glptt-8048d229e93509f47761d681d3548694f53a3bc4'
          GITLAB_PROJECT_ID: 60935746
        run: |
          curl --request POST \
            --form "token=$GITLAB_TOKEN" \
            --form "ref=main" \
            --form "variables[BUILD_TRIGGER]=true" \
            --form "variables[PIPELINE_TYPE]=infra" \
            "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/trigger/pipeline"
